export const infoItemList = [
    {
        firstPage: false,
        picsrc: import.meta.env.VITE_BASE + "/dataInterpretation.png",
        // routerPath: "dataInterpretation2",
        routerPath:"/bankManage/monitor/gnss",
        processPicSrc: import.meta.env.VITE_BASE + "/model-process.png",
        name: "数据融合解译模型",
        description: "数据融合解译模型是一个实时数据解析系统，旨在将GNSS、孔隙水压力计、应力桩和测斜仪等部署在河岸的设备实时传输的数据进行解析入库，以监测河岸稳定性、水文地质勘测和工程安全预警。用户可以通过该模型可以获取到河岸边各设备传来的测量数据。",
        application: "河岸稳定性监测，水文地质勘测，工程安全预警",
        usescene: "河岸工程建设前期评估，河岸改造工程实时监测，河岸生态环境保护",
        input: "GNSS设备原始数据、孔隙水压力计设备原始数据、应力桩设备原始数据、测斜仪设备原始数据、设备位置信息",
        output: "GNSS解译数据、孔隙水压力计解译数据、应力桩解译数据、测斜仪解译数据",
    },
    {
        firstPage: false,
        picsrc: import.meta.env.VITE_BASE + "/soilAnalysis.png",
        routerPath: "soilAnalysis",
        processPicSrc: import.meta.env.VITE_BASE + "/model-process.png",
        name: "土体变形分析模型",
        description: "土体变形分析模型描述了土体受剪切引起的崩塌和由河道水流冲刷及河岸坡脚物质迁移引起的侵蚀两种不同的过程,包括土体稳定性分析和河岸坡脚侵蚀分析。土体稳定分析主要采用极限平衡法计算多层土体岸坡的安全系数(Fs)，以分析河岸是否稳定。坡脚侵蚀分析用来预测由水流冲刷引起的河岸坡脚侵蚀速率及侵蚀量, 当侵蚀量到达一定程度时反馈作用于岸坡土体。",
        application: "土体变形分析，河岸侵蚀研究",
        usescene: "河岸工程规划设计阶段，河岸环境保护项目实施前的风险评估，河岸退化治理方案的优化设计",
        input: "岸坡坐标，流量参数，河道坡度，河床、岸坡和趾部材料类型，侵蚀保护措施",
        output: "侵蚀量",
    },
    {
        firstPage: false,
        picsrc: import.meta.env.VITE_BASE + "/stabilityAnalysis.png",
        routerPath: "stabilityAnalysis",
        processPicSrc: import.meta.env.VITE_BASE + "/model-process.png",
        name: "岸坡稳定性分析模型",
        description: "岸坡稳定性分析模型用于分析引起崩岸的近岸动力变化和演变因素，并实现相关指标的自动化提取。具体功能包括近岸动力分析功能：计算典型水文条件下的近岸动力，提供水动力分析，包括水位分析、流速分析等功能；近岸演变分析功能：提供岸坡坡度分析、近岸滩槽高差分析等近岸岸坡演变分析功能。",
        application: "土地利用规划，自然灾害风险评估，生态环境保护，水资源管理",
        usescene: "岸坡工程设计阶段，岸坡环境保护项目，岸坡退化治理方案优化，水利工程规划与管理",
        input: "岸坡坐标，土壤类型，植被覆盖，水位或孔隙水压力，土壤加固和地表超载",
        output: "地形图（中间变量），冲淤图（中间变量），安全系数",
    },
    {
        firstPage: false,
        picsrc: import.meta.env.VITE_BASE + "/riskWarning.png",
        routerPath: "riskWarning",
        processPicSrc: import.meta.env.VITE_BASE + "/model-process.png",
        name: "风险预警模型",
        description: "风险预警模型模型用于提供岸坡断面的实时预警和风险评估。具体功能包括单指标实时预警和多指标风险评估功能。单指标实时预警通过土体表面位移，内部变形、孔隙水压力和应力应变等实时监测数据，实现崩岸实时预警。多指标风险评估功能综合考虑近岸动力条件和冲淤变化，根据相关预警指标体系、权重和阈值计算，实现指定断面崩岸风险大小的评估。",
        application: "河岸管理与规划，灾害风险管理，城市规划与建设",
        usescene: "河岸管理与维护，灾害应急响应",
        input: "岸坡稳定性分析结果，土体变形分析结果，崩岸指标权重",
        output: "崩塌概率计算结果，社会经济损失风险矩阵，预警等级",
    },
]