server:
  port: 8989

spring:
  data:
    mongodb:
      database: bank
      authentication-database: admin
      uri: mongodb://localhost:27017/bank
  datasource:
    hikari:
      maxLifeTime: 120000
      idle-timeout: 0
      #      jdbc-url: jdbc:postgresql://192.168.1.131:5432/bankdemo?stringtype=unspecified
    default:
      url: jdbc:postgresql:////localhost:5432//bank?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/resourceRepo/*/*.xml
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

multiIndex:
  condaEnv: Env1
  dataPath: C:/Project/Bank/data/modelData
  wholeDataPath: C:/Project/Bank/data/dataWhole
  resPath: C:/Project/Bank/data/modelRes/

tile:
  mzsTilePath: C:/Project/Bank/data/bank_collapse/rasterTile/
  worldTilePath: C:/Project/Bank/data/bank_collapse/baseMap
  nodeServicePath: C:/Project/Bank/data/node/index.js
  riverTilePath: C:/Project/Bank/data/bank_collapse/riverRasterTile/
  riverImagePath: C:/Project/Bank/data/bank_collapse/imageTiles/tiles/

video:
  yangzhong: C:/Project/Bank/data/video/125_1711267167.mp4

flowData:
  texturePath: C:/Project/Bank/data/flowData/flowFieldResourceArchive/