server:
  port: 8989

spring:
  data:
    mongodb:
#      username: bankAdmin
#      password: 20000601
#      host: 192.168.31.12
#      port: 27017
#      database: bank
#      authentication-database: admin
#      uri: mongodb://bankAdmin:20000601@192.168.31.12:27017/bank
      host: localhost
      port: 27017
      database: local
      uri: mongodb://localhost:27017/local
  datasource:
      #      jdbc-url: jdbc:postgresql://192.168.1.131:5432/bankdemo?stringtype=unspecified
#    url: jdbc:postgresql://192.168.1.3:5432/shore?stringtype=unspecified
    url: jdbc:postgresql://localhost:5432/shore?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/resourceRepo/*/*.xml
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    swagger-ui:
      enabled: true