server:
  port: 8989

spring:
  data:
    mongodb:
      database: bank
      authentication-database: admin
      uri: mongodb://172.21.212.165:17017/bank
  datasource:
    hikari:
      maxLifeTime: 120000
      idle-timeout: 0
      #      jdbc-url: jdbc:postgresql://192.168.1.131:5432/bankdemo?stringtype=unspecified
    default:
      url: jdbc:postgresql://172.21.212.165:5431/bank?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456
mybatis:
  mapper-locations: classpath:mapper/resourceRepo/*/*.xml
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

multiIndex:
  condaEnv: Env1
  dataPath: /usr/local/resource/data/modelData
  wholeDataPath: /usr/local/resource/data/dataWhole
  resPath: /usr/local/resource/data/modelRes/

tile:
  mzsTilePath: /usr/local/resource/data/bank_collapse/rasterTile/
  worldTilePath: /usr/local/resource/data/bank_collapse/baseMap
  nodeServicePath: /usr/local/resource/data/node/index.js
  riverTilePath: /usr/local/resource/data/bank_collapse/riverRasterTile/
  riverImagePath: /usr/local/resource/data/bank_collapse/imageTiles/tiles/

video:
  yangzhong: /usr/local/resource/data/video/125_1711267167.mp4

flowData:
  texturePath: /usr/local/resource/data/flowData/flowFieldResourceArchive/