server:
  port: 8989

spring:
  data:
    mongodb:
      username: bankAdmin
      password: 20000601
      host: 192.168.1.6
      port: 27017
      database: bank
      authentication-database: admin
      uri: mongodb://bankAdmin:20000601@127.0.0.1:27017/bank
  datasource:
    hikari:
      maxLifeTime: 600000
      #      jdbc-url: jdbc:postgresql://192.168.1.131:5432/bankdemo?stringtype=unspecified
    url: jdbc:postgresql://192.168.1.3:5432/shore?stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/resourceRepo/*/*.xml
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

