server:
  port: 8989

spring:
  data:
    mongodb:
      database: bank_0301
      authentication-database: admin
      uri: mongodb://localhost:27017/bank_0301
  datasource:
    hikari:
      maxLifeTime: 120000
      idle-timeout: 0
    default:
      #      jdbc-url: jdbc:postgresql://192.168.1.131:5432/bankdemo?stringtype=unspecified
      url: jdbc:postgresql://localhost:5432/shore_0327?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: QWERBOOM123
mybatis:
  mapper-locations: classpath:mapper/resourceRepo/*/*.xml
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

mzsTilePath: E:/WATER/BankCollapse/backdata/rasterTIle/
