server:
  port: 8989

spring:
  data:
    mongodb:
      database: bank
      authentication-database: admin
      uri: mongodb://bankAdmin:20000601@localhost:27017/bank
  datasource:
    hikari:
      maxLifeTime: 120000
      idle-timeout: 0
    default:
      url: jdbc:postgresql://localhost:5432/bank_dev?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 20000601
  mail:
    host: smtp.qq.com
    port: 465
    username: 1275441282@qq.com
    password: ezuxlysqewrgfhhi
    from: 1275441282@qq.com
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true #启动debug调试
        smtp:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置

mybatis:
  mapper-locations: classpath:mapper/resourceRepo/*/*.xml
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

tile:
  mzsTilePath: D:/2024-work/shore_collapse/data/DEM/rasterTIle/
  worldTilePath: D:/2024-work/shore_collapse/data/mbtiles/data
  nodeServicePath: D:\2024-work\shore_collapse\code\node\index.js
  riverTilePath: D:/2024-work/shore_collapse/data/riverRasterTile/
  riverImagePath: D:/2024-work/shore_collapse/tiles/worldImage/tiles/

video:
  yangzhong: D:\2024-work\shore_collapse\data\video\125_1711267167.mp4

multiIndex:
  condaEnv: bankModel
  dataPath: D:\2024-work\shore_collapse\model\modelData
  wholeDataPath: D:\2024-work\shore_collapse\model\dataWhole
  resPath: D:\2024-work\shore_collapse\model\modelRes\

sms:
  accessTokenLoc: D:\2024-work\AccessKey.json
  signName: 江苏长江崩岸监测预警系统
#  verifyTemplateCode: SMS_465975002
  verifyTemplateCode: SMS_468300113

flowData:
  texturePath: D:/2024-work/shore_collapse/data/flowData/flowFieldResourceArchive/
