server:
  port: 8989

spring:
  data:
    mongodb:
      database: bank
      authentication-database: admin
      uri: mongodb://10.32.37.72:17017/bank
  datasource:
    hikari:
      maxLifeTime: 120000
      idle-timeout: 0
    default:
      database: bank
      ip: 10.32.37.72
      port: 15431
      url: jdbc:postgresql://10.32.37.72:15431/bank?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456
    public:
      database: bank
      ip: 10.32.37.72
      port: 15432
      url: jdbc:postgresql://10.32.37.72:15432/bank?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: nhri_admin123456
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
mybatis:
  mapper-locations: classpath:mapper/resourceRepo/*/*.xml
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

multiIndex:
  condaEnv: Env1
  dataPath: /usr/local/resource/data/modelData
  wholeDataPath: /usr/local/resource/data/dataWhole
  resPath: /usr/local/resource/data/modelRes/

tile:
  mzsTilePath: /usr/local/resource/data/bank_collapse/rasterTile/
  worldTilePath: /usr/local/resource/data/bank_collapse/baseMap
  nodeServicePath: /usr/local/resource/data/node/index.js
  riverTilePath: /usr/local/resource/data/bank_collapse/riverRasterTile/
  riverImagePath: /usr/local/resource/data/bank_collapse/imageTiles/tiles/

staticData:
  tifTilePath: /usr/local/resource/data/staticData/tifTile
  vectorDataPath: /usr/local/resource/data/staticData/vectorData
  draftDataPath: /usr/local/resource/data/staticData/draftData
  waterConditionPath: /usr/local/resource/data/staticData/waterCondition
  pictureDataPath: /usr/local/resource/data/staticData/pictureData
  knowledgePath:
    picture: /usr/local/resource/data/staticData/knowledge/picture
    pdf: /usr/local/resource/data/staticData/knowledge/pdf
    video: /usr/local/resource/data/staticData/knowledge/video
    others: /usr/local/resource/data/staticData/knowledge/others


flowData:
  texturePath: /usr/local/resource/data/flowData/flowFieldResourceArchive/

waterCondition:
  url: http://10.32.37.88:8821

modelServer:
  url: http://10.32.37.72:18000
  storageLimit: 50
  caseLimit: 50

loginFunction: "no"