server:
  port: 8989

spring:
  data:
    mongodb:
      database: bank
      authentication-database: admin
      uri: mongodb://localhost:27017/bank
  datasource:
    hikari:
      maxLifeTime: 120000
      idle-timeout: 0
    default:
      database: bank_new
      ip: localhost
      port: 5432
      url: jdbc:postgresql://localhost:5432/bank_new?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: nhri_admin123456
    public:
      database: bank
      ip: 119.45.198.54
      port: 5432
      url: jdbc:postgresql://119.45.198.54:5432/bank?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: nhri_admin123456
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mybatis:
    mapper-locations: classpath:mapper/resourceRepo/*/*.xml
    configuration:
      call-setters-on-nulls: true
  mail:
    host: smtp.qq.com
    port: 465
    username: 1275441282@qq.com
    password: ezuxlysqewrgfhhi
    from: 1275441282@qq.com
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true #启动debug调试
        smtp:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory #SSL连接配置
springfox:
  documentation:
    swagger-ui:
      enabled: true

multiIndex:
  condaEnv: Env1
  dataPath: E:\bankAppData\modelData
  wholeDataPath: E:\bankAppData\dataWhole
  resPath: E:/bankAppData/modelRes/

tile:
  mzsTilePath: E:\bankAppData\rasterTile\
  worldTilePath: E:\bankAppData\baseMap
  nodeServicePath: E:\bankAppData\baseMapService\index.js
  riverTilePath: E:\bankAppData\riverRasterTile\
  riverImagePath: E:\bankAppData\imageTiles\tiles\

staticData:
  tifTilePath: E:\bankAppData\staticData\tifTile
  vectorDataPath: E:\bankAppData\staticData\vectorData
  waterConditionPath: E:\bankAppData\staticData\waterCondition
  draftDataPath: E:\bankAppData\staticData\draftData

waterCondition:
  url: http://10.32.22.202:8001

video:
  yangzhong: E:\bankAppData\video\125_1711267167.mp4

sms:
  accessTokenLoc: E:\bankAppData\AccessKey.json
  signName: 江苏长江崩岸监测预警系统
  verifyTemplateCode: SMS_465975002

flowData:
  texturePath: E:/bankAppData/flowData/flowFieldResourceArchive/

modelServer:
  url: http://127.0.0.1:8000
  storageLimit: 50
  caseLimit: 50

loginFunction: "no"